version: '3.8'
services:
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/app
    command: npm start
    restart: unless-stopped
    tty: true
