version: '3.8'

services:
  discord-music-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: discord-dg-music-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env
    volumes:
      # Mount data directory for persistence using named volume
      - music-bot-data:/app/data
      # Optional: mount logs if implemented  
      - music-bot-logs:/app/logs
    networks:
      - music-bot-network
    # Optional healthcheck
    healthcheck:
      test: ['CMD', 'node', '-e', 'process.exit(0)']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Limit resources to prevent excessive usage
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

networks:
  music-bot-network:
    driver: bridge
    name: dg-music-bot-network

volumes:
  music-bot-data:
    driver: local
    name: dg-music-bot-data
  music-bot-logs:
    driver: local
    name: dg-music-bot-logs
